from .prompts import (
    PRODUCT_EXTRACTION_PROMPT,
    CLARIFICATION_PROMPT,
    RECOMMENDATION_PROMPT,
    REPORT_PROMPT
)

__all__ = [
    "PRODUCT_EXTRACTION_PROMPT",
    "CLARIFICATION_PROMPT",
    "RECOMMENDATION_PROMPT",
    "REPORT_PROMPT"
]
